config/routes.rb
Vibes::Application.routes.draw do
  root 'ideas#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations' }

  resources :users
  resources :ideas do
    get '/upvote' => 'ideas#upvote'
    get '/downvote' => 'ideas#downvote'
  end

  resources :comments, only: :create

  namespace :api, defaults: { format: :json } do
    scope module: :v1 do
      resources :ideas, only: [:index, :show] do
        get '/upvote' => 'ideas#upvote'
        get '/downvote' => 'ideas#downvote'
        get '/vote_for_current_user' => 'ideas#vote_for_current_user'
      end

      get '/users/current' => 'users#current'
    end
  end
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  has_many :comments

  validates :name, :leader, :description, :user, presence: true

  def vote_from_user (user)
    votes.where(user: user).first
  end

  def vote_from_user? (user)
    vote_from_user(user).present?
  end

  def upvotes
    votes.where(kind: 1)
  end

  def downvotes
    votes.where(kind: -1)
  end

  def upvote_count
    upvotes.count
  end

  def downvote_count
    downvotes.count
  end

  def score
    votes.sum(:kind)
  end
end

app/controllers/api/v1/ideas_controller.rb
module Api
  module V1
    class IdeasController < ApiController
      def index
        respond_with(Idea.all)
      end

      def show
        @idea = Idea.find(params[:id])

        render json: @idea.as_json(methods: [:score, :upvote_count, :downvote_count])
      end

      def upvote
        @idea = Idea.find(params[:idea_id])

        if current_user == @idea.user
          render json: { error: "you cannot vote you on your own idea!" }
        else


          if vote = @idea.vote_from_user(current_user)
            vote.kind = 1
            vote.save
          else
            vote = @idea.votes.build({user: current_user, kind: 1})
            @idea.save
          end

          render json: vote.as_json
        end
      end

      def downvote
        @idea = Idea.find(params[:idea_id])

        if current_user == @idea.user
          render json: { error: "you cannot vote you on your own idea!" }
        else

          if @idea.vote_from_user? current_user
            vote = @idea.vote_from_user(current_user)
            vote.kind = -1
            vote.save
          else
            vote = @idea.votes.build({user: current_user, kind: -1})
            @idea.save
          end

          render json: vote.as_json
        end
      end

      def vote_for_current_user
        vote = Idea.find(params[:idea_id]).votes.where(user: current_user).first

        render json: vote.as_json
      end
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @ideas = Idea.all
  end

  def show
    @idea = Idea.find(params[:id])
    @comments = Comment.where(idea: @idea)
    @comment = Comment.new({idea: @idea})
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(params.require(:idea).permit(:name, :leader, :description))
    @idea.user = current_user
    @idea.save
    redirect_to idea_path @idea
  end

  def upvote
    @idea = Idea.find(params[:idea_id])

    if current_user == @idea.user
      redirect_to idea_path(@idea)
    else

      if @idea.vote_from_user? current_user
        vote = @idea.vote_from_user(current_user)
        vote.kind = 1
        vote.save
      else
        @idea.votes.build({user: current_user, kind: 1})
        @idea.save
      end
      redirect_to idea_path(@idea)
    end
  end

  def downvote
    @idea = Idea.find(params[:idea_id])

    if current_user == @idea.user
      redirect_to idea_path(@idea)
    else

      if @idea.vote_from_user? current_user
        vote = @idea.vote_from_user(current_user)
        vote.kind = -1
        vote.save
      else
        @idea.votes.build({user: current_user, kind: -1})
        @idea.save
      end

      redirect_to idea_path(@idea)
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.haml
= semantic_form_for idea do |f|
  %fieldset
    %legend= :idea

    = f.input :name
    = f.input :leader
    = f.input :description

    = f.submit

app/views/ideas/index.html.haml
%h2 Ideas

= link_to 'Create Idea', new_idea_path, class: :button

.sixteen.columns

- @ideas.each do |idea|
  .four.columns.idea
    = image_tag 'exampleLogo.png', class: 'ideaLogo'
    %h2.ideaName= link_to idea.name, idea

    %p.ideaLeader= idea.leader

    .ideaFooter
      .msgCount
        %h6= idea.comments.count
      .moreInfo=link_to 'More...', idea

app/views/ideas/new.html.haml
= render 'form', idea: @idea

app/views/ideas/show.html.haml
.sixteen.columns
  .twelve.columns.alpha.clearfix
    .ideaHeader
      .four.columns.ideaLogo.clearfix
        =image_tag 'exampleLogoFull.png'
      .eight.columns.ideaBrief
        %h1.ideaName= @idea.name
        %p.ideaLeader.bigger= @idea.leader
    .ideaDescription
      %h3= @idea.description
  .four.columns.omega
    .ideaOwner
      %h4 Idea Ownership
      =image_tag 'exampleUser.jpg', class: 'userAvatar'
      %h4= @idea.user.full_name
    .ideaVotes
      %h6 Votes
      %div.voteIcons
        - if user_signed_in?
          .thumbIcon.up{ :'data-bind' => 'click: upvote, css: thumbUpIconClasses' }
          .votes.up{ :'data-bind' => 'text: idea().upVoteCount' }
          .thumbIcon.down{ :'data-bind' => 'click: downvote, css: thumbDownIconClasses' }
          .votes.down{ :'data-bind' => 'text: idea().downVoteCount' }
        - else
          Want to vote?
          = link_to 'Sign In', new_user_session_path

.sixteen.columns.ideaMessages
  %h4 Message History
  = render 'comments/comments', comment: @comment, comments: @comments